/** Architecture de navigation de chaque espace (cf. cahier des charges N°1). */
export const NAVIGATION = {
  eleve: [
    { key: '', label: 'Tableau de bord', icon: 'home' },
    { key: 'assistant', label: 'Assistant IA', icon: 'sparkles' },
    { key: 'resultats', label: 'Résultats', icon: 'chart' },
    { key: 'devoirs', label: 'Devoirs', icon: 'edit' },
    { key: 'cours', label: 'Cours', icon: 'book' },
    { key: 'bibliotheque', label: 'Bibliothèque', icon: 'library' },
    { key: 'entrainement', label: 'Entraînement', icon: 'brain' },
    { key: 'enseignants', label: 'Enseignants', icon: 'teacher' },
    { key: 'emploi-du-temps', label: 'Emploi du temps', icon: 'calendar' },
    { key: 'progression', label: 'Progression', icon: 'trend' },
    { key: 'messages', label: 'Messages', icon: 'message' },
    { key: 'notifications', label: 'Notifications', icon: 'bell' },
    { key: 'compte', label: 'Mon compte', icon: 'lock' },
  ],
  parent: [
    { key: '', label: 'Tableau de bord', icon: 'home' },
    { key: 'enfants', label: 'Mes enfants', icon: 'child' },
    { key: 'fiche', label: 'Fiche de vie', icon: 'folder' },
    { key: 'resultats', label: 'Résultats', icon: 'chart' },
    { key: 'bulletins', label: 'Bulletins', icon: 'file' },
    { key: 'devoirs', label: 'Devoirs', icon: 'edit' },
    { key: 'presences', label: 'Présences', icon: 'checkCircle' },
    { key: 'sorties', label: 'Sorties', icon: 'door' },
    { key: 'paiements', label: 'Paiements', icon: 'wallet' },
    { key: 'emploi-du-temps', label: 'Emploi du temps', icon: 'calendar' },
    { key: 'enseignants', label: 'Enseignants', icon: 'teacher' },
    { key: 'messages', label: 'Messages', icon: 'message' },
    { key: 'notifications', label: 'Notifications', icon: 'bell' },
    { key: 'compte', label: 'Mon compte', icon: 'lock' },
  ],
  enseignant: [
    { key: '', label: 'Tableau de bord', icon: 'home' },
    { key: 'classes', label: 'Mes classes', icon: 'users' },
    { key: 'eleves', label: 'Mes élèves', icon: 'user' },
    { key: 'devoirs', label: 'Devoirs', icon: 'edit' },
    { key: 'bibliotheque', label: 'Bibliothèque', icon: 'library' },
    { key: 'notes', label: 'Notes', icon: 'chart' },
    { key: 'progression', label: 'Progression', icon: 'trend' },
    { key: 'presences', label: 'Présences', icon: 'checkCircle' },
    { key: 'emploi-du-temps', label: 'Emploi du temps', icon: 'calendar' },
    { key: 'messages', label: 'Messages', icon: 'message' },
    { key: 'notifications', label: 'Annonces & notifications', icon: 'bell' },
    { key: 'compte', label: 'Mon compte', icon: 'lock' },
  ],
  admin: [
    { key: '', label: 'Dashboard', icon: 'home' },
    { key: 'eleves', label: 'Élèves', icon: 'user' },
    { key: 'enseignants', label: 'Enseignants', icon: 'teacher' },
    { key: 'classes', label: 'Classes', icon: 'school' },
    { key: 'matieres', label: 'Matières', icon: 'book' },
    { key: 'emploi-du-temps', label: 'Emploi du temps', icon: 'calendar' },
    { key: 'notes', label: 'Notes & bulletins', icon: 'file' },
    { key: 'presences', label: 'Présences', icon: 'checkCircle' },
    { key: 'sorties', label: 'Sorties', icon: 'door' },
    { key: 'scolarite', label: 'Scolarité', icon: 'wallet' },
    { key: 'communication', label: 'Communication', icon: 'megaphone' },
    { key: 'bibliotheque', label: 'Bibliothèque', icon: 'library' },
    { key: 'messages', label: 'Messages', icon: 'message' },
    { key: 'parametres', label: 'Paramètres', icon: 'settings' },
    { key: 'journal', label: 'Sécurité & journal', icon: 'shield' },
    { key: 'compte', label: 'Mon compte', icon: 'lock' },
  ],
};

export function sectionLabel(role, key) {
  return NAVIGATION[role]?.find((i) => i.key === key)?.label || '';
}
